### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by tuntematonjr** [tuntematonjr/Tun-Respawn-System#17]
my random to do list
- [x] add player/side tickets waiting area text
- [x] add seperate contested variables to each side
- [x] add sound to respawn area, when les than 30s
- [x] save nanoseconds at whoToNotify count
- [x] add side categories to msp things
- [x] unify getTicket fnc
- [x] unify bleed tickets
- [x] Respawn template
- [x] Add allowed spectate sides
- [x] Add ability to check contested status
- [x] Visual markers for contest area check
- [x] Fix delayed respawn getting respawned twice
- [ ] ability to spectate at respawn. Own side only, 1st person
